// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back_net.Models;

#nullable disable

namespace back_net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back_net.Models.AnotacionesOpt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdOpt")
                        .HasColumnType("integer")
                        .HasColumnName("id_opt");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("anotaciones_opt_pkey");

                    b.HasIndex("IdOpt");

                    b.HasIndex("IdUsuario");

                    b.ToTable("anotaciones_opt", (string)null);
                });

            modelBuilder.Entity("back_net.Models.ComentariosOp", b =>
                {
                    b.Property<int>("IdCom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_com");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdCom"));

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdOp")
                        .HasColumnType("integer")
                        .HasColumnName("id_op");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<bool?>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("leido");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.HasKey("IdCom")
                        .HasName("comentarios_op_pkey");

                    b.HasIndex("IdOp");

                    b.HasIndex("IdUsuario");

                    b.ToTable("comentarios_op", (string)null);
                });

            modelBuilder.Entity("back_net.Models.InspeccionesCalidad", b =>
                {
                    b.Property<int>("IdInspeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_inspeccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdInspeccion"));

                    b.Property<string>("CodigoInspeccion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo_inspeccion");

                    b.Property<bool?>("CosturasOk")
                        .HasColumnType("boolean")
                        .HasColumnName("costuras_ok");

                    b.Property<DateTime?>("FechaInspeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inspeccion")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("FotoEvidencia")
                        .HasColumnType("bytea")
                        .HasColumnName("foto_evidencia");

                    b.Property<int>("IdOp")
                        .HasColumnType("integer")
                        .HasColumnName("id_op");

                    b.Property<int?>("IdUsuarioInspector")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_inspector");

                    b.Property<bool?>("ListaParaEntrega")
                        .HasColumnType("boolean")
                        .HasColumnName("lista_para_entrega");

                    b.Property<string>("NotaAdicional")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<bool?>("PiezasUnidas")
                        .HasColumnType("boolean")
                        .HasColumnName("piezas_unidas");

                    b.Property<string>("ResultadoFinal")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("resultado_final");

                    b.Property<bool?>("TelaSinDefectos")
                        .HasColumnType("boolean")
                        .HasColumnName("tela_sin_defectos");

                    b.HasKey("IdInspeccion")
                        .HasName("inspecciones_calidad_pkey");

                    b.HasIndex("IdOp");

                    b.HasIndex("IdUsuarioInspector");

                    b.HasIndex(new[] { "CodigoInspeccion" }, "inspecciones_calidad_codigo_inspeccion_key")
                        .IsUnique();

                    b.ToTable("inspecciones_calidad", (string)null);
                });

            modelBuilder.Entity("back_net.Models.Molde", b =>
                {
                    b.Property<int>("IdMolde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_molde");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdMolde"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<byte[]>("ArchivoBlob")
                        .HasColumnType("bytea")
                        .HasColumnName("archivo_blob");

                    b.Property<string>("CodigoMolde")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("codigo_molde");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ExtensionArchivo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extension_archivo");

                    b.Property<DateTime?>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("IdUsuarioSubida")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_subida");

                    b.Property<string>("NombreArchivoOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo_original");

                    b.Property<string>("NombreMolde")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_molde");

                    b.Property<long?>("PesoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("peso_bytes");

                    b.Property<string>("VersionMolde")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("version_molde");

                    b.HasKey("IdMolde")
                        .HasName("moldes_pkey");

                    b.HasIndex("IdUsuarioSubida");

                    b.ToTable("moldes", (string)null);
                });

            modelBuilder.Entity("back_net.Models.Optimizacione", b =>
                {
                    b.Property<int>("IdOpt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_opt");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdOpt"));

                    b.Property<decimal?>("AprovechamientoPorcent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("aprovechamiento_porcent");

                    b.Property<byte[]>("ArchivoDxf")
                        .HasColumnType("bytea")
                        .HasColumnName("archivo_dxf");

                    b.Property<decimal?>("DesperdicioM")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("desperdicio_m");

                    b.Property<bool>("EsOptimaFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'generado'::character varying");

                    b.Property<DateTime?>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("GeneradoPor")
                        .HasColumnType("integer")
                        .HasColumnName("generado_por");

                    b.Property<string>("GiroPermitido")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("giro_permitido")
                        .HasDefaultValueSql("'0'::character varying");

                    b.Property<int?>("IdMolde")
                        .HasColumnType("integer")
                        .HasColumnName("id_molde");

                    b.Property<int>("IdOp")
                        .HasColumnType("integer")
                        .HasColumnName("id_op");

                    b.Property<byte[]>("ImagenPrevisualizacion")
                        .HasColumnType("bytea")
                        .HasColumnName("imagen_previsualizacion");

                    b.Property<string>("MetricasJson")
                        .HasColumnType("text");

                    b.Property<string>("NombreArchivoDxf")
                        .HasColumnType("text");

                    b.Property<string>("NombreVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_version");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("OrientacionPiezas")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("orientacion_piezas")
                        .HasDefaultValueSql("'restringida'::character varying");

                    b.Property<string>("RutaPngGenerado")
                        .HasColumnType("text");

                    b.Property<decimal?>("TelaUtilizadaM")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("tela_utilizada_m");

                    b.Property<int?>("TiempoEstimadoMin")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_estimado_min");

                    b.Property<short>("VersionNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("version_num");

                    b.HasKey("IdOpt")
                        .HasName("optimizaciones_pkey");

                    b.HasIndex("GeneradoPor");

                    b.HasIndex("IdMolde");

                    b.HasIndex(new[] { "IdOp" }, "idx_opt_op");

                    b.ToTable("optimizaciones", (string)null);
                });

            modelBuilder.Entity("back_net.Models.OrdenProduccion", b =>
                {
                    b.Property<int>("IdOp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_op");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdOp"));

                    b.Property<byte[]>("ArchivoBlob")
                        .HasColumnType("bytea")
                        .HasColumnName("archivo_blob");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("CodigoOp")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo_op");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text")
                        .HasColumnName("comentarios");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'pendiente'::character varying");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<int?>("IdUsuarioCreador")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_creador");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modelo");

                    b.Property<string>("Talla")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("talla");

                    b.HasKey("IdOp")
                        .HasName("orden_produccion_pkey");

                    b.HasIndex("IdUsuarioCreador");

                    b.HasIndex(new[] { "Estado" }, "idx_op_estado");

                    b.HasIndex(new[] { "CodigoOp" }, "orden_produccion_codigo_op_key")
                        .IsUnique();

                    b.ToTable("orden_produccion", (string)null);
                });

            modelBuilder.Entity("back_net.Models.OrdenRollo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdOp")
                        .HasColumnType("integer")
                        .HasColumnName("id_op");

                    b.Property<int>("IdRollo")
                        .HasColumnType("integer")
                        .HasColumnName("id_rollo");

                    b.Property<decimal>("MetrajeAsignadoM")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("metraje_asignado_m");

                    b.HasKey("Id")
                        .HasName("orden_rollos_pkey");

                    b.HasIndex("IdOp");

                    b.HasIndex("IdRollo");

                    b.ToTable("orden_rollos", (string)null);
                });

            modelBuilder.Entity("back_net.Models.Role", b =>
                {
                    b.Property<short>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_role");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("IdRole"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_role");

                    b.HasKey("IdRole")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "NombreRole" }, "roles_nombre_role_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("back_net.Models.RollosTela", b =>
                {
                    b.Property<int>("IdRollo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rollo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdRollo"));

                    b.Property<decimal>("AltoCm")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("alto_cm");

                    b.Property<decimal>("AnchoCm")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("ancho_cm");

                    b.Property<string>("CodigoRollo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo_rollo");

                    b.Property<string>("Color")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("color");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'disponible'::character varying");

                    b.Property<DateTime?>("FechaRecepcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recepcion")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("IdUsuarioRegistro")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_registro");

                    b.Property<decimal>("MetrajeM")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("metraje_m");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("proveedor");

                    b.Property<string>("TipoTela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_tela");

                    b.HasKey("IdRollo")
                        .HasName("rollos_tela_pkey");

                    b.HasIndex("IdUsuarioRegistro");

                    b.HasIndex(new[] { "Estado" }, "idx_rollo_estado");

                    b.HasIndex(new[] { "CodigoRollo" }, "rollos_tela_codigo_rollo_key")
                        .IsUnique();

                    b.ToTable("rollos_tela", (string)null);
                });

            modelBuilder.Entity("back_net.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correo");

                    b.Property<DateTime?>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("IdRole")
                        .HasColumnType("smallint")
                        .HasColumnName("id_role");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("IdUsuario")
                        .HasName("usuarios_pkey");

                    b.HasIndex("IdRole");

                    b.HasIndex(new[] { "Correo" }, "usuarios_correo_key")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("back_net.Models.AnotacionesOpt", b =>
                {
                    b.HasOne("back_net.Models.Optimizacione", "IdOptNavigation")
                        .WithMany("AnotacionesOpts")
                        .HasForeignKey("IdOpt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("anotaciones_opt_id_opt_fkey");

                    b.HasOne("back_net.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("AnotacionesOpts")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("anotaciones_opt_id_usuario_fkey");

                    b.Navigation("IdOptNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("back_net.Models.ComentariosOp", b =>
                {
                    b.HasOne("back_net.Models.OrdenProduccion", "IdOpNavigation")
                        .WithMany("ComentariosOps")
                        .HasForeignKey("IdOp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("comentarios_op_id_op_fkey");

                    b.HasOne("back_net.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("ComentariosOps")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("comentarios_op_id_usuario_fkey");

                    b.Navigation("IdOpNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("back_net.Models.InspeccionesCalidad", b =>
                {
                    b.HasOne("back_net.Models.OrdenProduccion", "IdOpNavigation")
                        .WithMany("InspeccionesCalidads")
                        .HasForeignKey("IdOp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("inspecciones_calidad_id_op_fkey");

                    b.HasOne("back_net.Models.Usuario", "IdUsuarioInspectorNavigation")
                        .WithMany("InspeccionesCalidads")
                        .HasForeignKey("IdUsuarioInspector")
                        .HasConstraintName("inspecciones_calidad_id_usuario_inspector_fkey");

                    b.Navigation("IdOpNavigation");

                    b.Navigation("IdUsuarioInspectorNavigation");
                });

            modelBuilder.Entity("back_net.Models.Molde", b =>
                {
                    b.HasOne("back_net.Models.Usuario", "IdUsuarioSubidaNavigation")
                        .WithMany("Moldes")
                        .HasForeignKey("IdUsuarioSubida")
                        .HasConstraintName("moldes_id_usuario_subida_fkey");

                    b.Navigation("IdUsuarioSubidaNavigation");
                });

            modelBuilder.Entity("back_net.Models.Optimizacione", b =>
                {
                    b.HasOne("back_net.Models.Usuario", "GeneradoPorNavigation")
                        .WithMany("Optimizaciones")
                        .HasForeignKey("GeneradoPor")
                        .HasConstraintName("optimizaciones_generado_por_fkey");

                    b.HasOne("back_net.Models.Molde", "IdMoldeNavigation")
                        .WithMany("Optimizaciones")
                        .HasForeignKey("IdMolde")
                        .HasConstraintName("optimizaciones_id_molde_fkey");

                    b.HasOne("back_net.Models.OrdenProduccion", "IdOpNavigation")
                        .WithMany("Optimizaciones")
                        .HasForeignKey("IdOp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("optimizaciones_id_op_fkey");

                    b.Navigation("GeneradoPorNavigation");

                    b.Navigation("IdMoldeNavigation");

                    b.Navigation("IdOpNavigation");
                });

            modelBuilder.Entity("back_net.Models.OrdenProduccion", b =>
                {
                    b.HasOne("back_net.Models.Usuario", "IdUsuarioCreadorNavigation")
                        .WithMany("OrdenProduccions")
                        .HasForeignKey("IdUsuarioCreador")
                        .HasConstraintName("orden_produccion_id_usuario_creador_fkey");

                    b.Navigation("IdUsuarioCreadorNavigation");
                });

            modelBuilder.Entity("back_net.Models.OrdenRollo", b =>
                {
                    b.HasOne("back_net.Models.OrdenProduccion", "IdOpNavigation")
                        .WithMany("OrdenRollos")
                        .HasForeignKey("IdOp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("orden_rollos_id_op_fkey");

                    b.HasOne("back_net.Models.RollosTela", "IdRolloNavigation")
                        .WithMany("OrdenRollos")
                        .HasForeignKey("IdRollo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("orden_rollos_id_rollo_fkey");

                    b.Navigation("IdOpNavigation");

                    b.Navigation("IdRolloNavigation");
                });

            modelBuilder.Entity("back_net.Models.RollosTela", b =>
                {
                    b.HasOne("back_net.Models.Usuario", "IdUsuarioRegistroNavigation")
                        .WithMany("RollosTelas")
                        .HasForeignKey("IdUsuarioRegistro")
                        .HasConstraintName("rollos_tela_id_usuario_registro_fkey");

                    b.Navigation("IdUsuarioRegistroNavigation");
                });

            modelBuilder.Entity("back_net.Models.Usuario", b =>
                {
                    b.HasOne("back_net.Models.Role", "IdRoleNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("usuarios_id_role_fkey");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("back_net.Models.Molde", b =>
                {
                    b.Navigation("Optimizaciones");
                });

            modelBuilder.Entity("back_net.Models.Optimizacione", b =>
                {
                    b.Navigation("AnotacionesOpts");
                });

            modelBuilder.Entity("back_net.Models.OrdenProduccion", b =>
                {
                    b.Navigation("ComentariosOps");

                    b.Navigation("InspeccionesCalidads");

                    b.Navigation("Optimizaciones");

                    b.Navigation("OrdenRollos");
                });

            modelBuilder.Entity("back_net.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("back_net.Models.RollosTela", b =>
                {
                    b.Navigation("OrdenRollos");
                });

            modelBuilder.Entity("back_net.Models.Usuario", b =>
                {
                    b.Navigation("AnotacionesOpts");

                    b.Navigation("ComentariosOps");

                    b.Navigation("InspeccionesCalidads");

                    b.Navigation("Moldes");

                    b.Navigation("Optimizaciones");

                    b.Navigation("OrdenProduccions");

                    b.Navigation("RollosTelas");
                });
#pragma warning restore 612, 618
        }
    }
}
